specVersion: "0.2.0"

name: "Subql-kitty"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-examples"

schema:
  file: "./schema.graphql"

network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3' # Polkadot
  # replace this one by user
  endpoint: "ws://host.docker.internal:9944"
  types: {
    "KittyIndex": "u32",
    "Kitty": "[u8; 16]",
  }
  typesBundle: {
    spec: {
      chainname: {
        rpc: {
          kitties: {
            getKittyPrice:{
                description: string,
                params: [
                  {
                    name: 'at',
                    type: 'BlockHash',
                    isHistoric: true,
                    isOptional: false
                  },
                  {
                    name: 'kittyIndex',
                    type: 'KittyIndex',
                    isOptional: false
                  }
                ],
                type: "Balance",
            }
          }
        }
      }
    }
  }

dataSources:
    - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleKittyCreated
          kind: substrate/EventHandler
          filter:
            module: kitties
            method: KittyCreated
        - handler: handleKittyBred
          kind: substrate/CallHandler
          filter:
            module: kitties
            method: breed
            success: true
        - handler: handleKittyTransferred
          kind: substrate/EventHandler
          filter:
            module: kitties
            method: KittyTransferred
