specVersion: "0.0.1"
description: "This subquery indexes bond,reward and slash of each block, summarize total earning of an account"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: "wss://polkadot.api.onfinality.io/public-ws"

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBond
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
        - handler: handleStakingReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleStakingSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleStakingSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed