specVersion: "0.2.0"

name: "Subql-validator-threshold"
version: "0.0.0"
description: "Indexes the least staking amount required for a validator to be elected."
repository: "https://github.com/subquery/subql-examples"

schema:
  file: "./schema.graphql"

network:
  genesisHash: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3" # Polkadot
  endpoint: "wss://polkadot.api.onfinality.io/public-ws"

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
