specVersion: "0.2.0"

name: "Subql-entityrelation"
version: "0.0.0"
description: "Indexes balance transfers between accounts, also indexes utility batchAll to find out the content of the extrinsic calls."
repository: "https://github.com/subquery/subql-examples"

schema:
  file: "./schema.graphql"

network:
  genesisHash: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3" # Polkadot
  endpoint: "wss://polkadot.api.onfinality.io/public-ws"
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
